//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iClassic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuSanXuat
    {
        public int Id { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> MaVaiId { get; set; }
        public int SoLuong { get; set; }
        public int Status { get; set; }
        public bool HasVai { get; set; }
        public int InvoiceId { get; set; }
        public int ProductTypeId { get; set; }
        public double DonGia { get; set; }
    
        public virtual LoaiVai LoaiVai { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
