//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iClassic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuChi
    {
        public int Id { get; set; }
        public string MucChi { get; set; }
        public double SoTien { get; set; }
        public string NguoiNhanPhieu { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
