//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iClassic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTypeValue
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public int ProductTypeFieldId { get; set; }
        public int CustomerId { get; set; }
    
        public virtual ProductTyeField ProductTyeField { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
