//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iClassic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMemberCard
    {
        public int Id { get; set; }
        public int MemberCardId { get; set; }
        public int ProductId { get; set; }
        public int Discount { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual MemberCard MemberCard { get; set; }
    }
}
