//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iClassic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int Id { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public string EmployeeId { get; set; }
        public double TotalSalary { get; set; }
        public string Note { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Tho Tho { get; set; }
    }
}
