//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcMean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInChiTieu
    {
        public int Id { get; set; }
        public decimal SoTien { get; set; }
        public string ForUserId { get; set; }
        public int ChiTieuId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual DsChiTieu DsChiTieu { get; set; }
    }
}
